name: My first workflow

on:
  push:
    branches: 
      - main
  workflow_dispatch:
jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello Actions!"
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: List files in repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.job }}
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ github.job }}
  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - run: echo ${{ github.job }}
  job4:
    runs-on: ubuntu-latest
    needs: [job2, job3]
    steps:
      - run: echo ${{ github.job }}
